sudo: required
services:
  - docker

before_install:
  - docker build -t uchestik/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true uchestik/react-test npm run test

# build images of all the services so they can be pushed to 
# docker hub
after_success:
  - docker build -t uchestik/fib-client ./frontend
  - docker build -t uchestik/fib-server ./server
  - docker build -t uchestik/fib-nginx ./nginx
  - docker build -t uchestik/fib-worker ./worker

  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to dockerhub
  - docker push uchestik/fib-client
  - docker push uchestik/fib-server
  - docker push uchestik/fib-nginx
  - docker push uchestik/fib-worker

#deployment instructions
deploy:
  # travis ci has built in providers such as aws, digital ocean etc.
  provider: elasticbeanstalk
  # the region of your beanstalk instance, look at the instance url
  region: "us-east-2"
  # app name as specifies in your beanstalk instance
  app: "multi-docker"
  # environment name
  env: "Multidocker-env"
  # travis will zip all your files and send them over to an s3 bucket
  # which is ultimately a hard drive. Then travis alerts elastic beanstalk to 
  # deploy the application. This s3 bucket is automatically generated
  bucker_name: "elasticbeanstalk-us-east-2-035969879236"
  # the elastic bean bucket will be re-used for every environment 
  # so for every environment a new folder will be created
  # by default this will be the app name
  bucket_path: "multi-docker"
  on:
    # deploy when code is pushed to the master branch
    branch: master
  # access keys have been saved as environment variables in travis
  # for extra security
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY